---
- name: lesson 3 with testing and loops
  hosts: local
  tasks:
    - name: Test with_items
      debug:
        msg: Hello World
      with_items:
        - 10.10.10.1
        - 10.10.20.1
        - 10.10.30.1
        - 10.10.40.1
        - 10.10.50.1

    - name: Test loop
      debug:
        msg: Hello World (loop)
      loop:
        - 10.10.10.1
        - 10.10.20.1
        - 10.10.30.1
        - 10.10.40.1
        - 10.10.50.1
