---
- name: Tags Example
  hosts: cisco
  gather_facts: false
  tasks:
    - cisco.ios.ios_facts:
      tags: facts_only

    - name: print ios_facts to stdout
      ansible.builtin.debug:
        var: ansibel_net_model

    - cisco.ios.ios_command:
        commands: show ip interface brief
      tags: show_ip
      register: output

    - ansible.builtin.debug:
        var: output
      tags: show_ip
